# Generated by Django 4.1.5 on 2023-01-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название аналитики')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статьи')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название счета')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название организации')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа (тип)')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата в документе')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.analytics')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.organization')),
            ],
            options={
                'verbose_name': 'Документ',
                'ordering': ['-time_create', 'name'],
            },
        ),
    ]
