# Generated by Django 4.1.5 on 2023-01-21 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_document_date_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата в документе'),
        ),
    ]
